package com.atu.WednesdaysWickedAdventures.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import jakarta.validation.constraints.Size;

/**
 * Represents a BOOKING entity in the Wednesdays Wicked Adventures system.
 * This class is mapped to the "bookings" collection in MongoDB.
 * 
 * @author	Mathieu Bizumuremyi 
 * @version	1.0 
 * @since	07-03-2025
 * 
 */
@Document(collection = "bookings")
public class Booking {

    /**
     * The unique identifier of the booking.
     * It must be null when creating a new booking, as it is generated by the database.
     */
    @Id
    @Null(message = "Id must be null for booking.")
    private String id;

    /**
     * The name of the customer making the booking.
     * It cannot be blank and must be between 5 and 250 characters long.
     */
    @NotBlank(message = "Customer name is required")
    @Size(min = 5, max = 250, message = "Customer name must be between 5 and 250 characters")
    private String customerName;
    
    /**
     * The email of the customer making the booking.
     * It cannot be blank.
     */
    @NotBlank(message = "Customer email is required")
    @Email(regexp = "[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,3}",
    		message = "Invalid email format")
    private String email;

    /**
     * The unique identifier of the event being booked.
     * It cannot be null.
     */
    @NotNull(message = "Event ID is required")
    private String eventId;

    /**
     * The number of tickets booked.
     * It cannot be null and must be between 0 and 25.
     */
    @NotNull(message = "Number of tickets is required")
    @Min(value = 0, message = "numberOfTickets should not be less than 0")
    @Max(value = 25, message = "numberOfTickets should not be greater than 25")
    private int numberOfTickets;

    /**
     * Default constructor for the Booking class.
     */
    public Booking() {}

    /**
     * Constructs a new Booking with the specified customer name, event ID, and number of tickets.
     *
     * @param customerName    The name of the customer making the booking.
     * @param eventId         The unique identifier of the event being booked.
     * @param numberOfTickets The number of tickets booked.
     */
    public Booking(String customerName, String email, String eventId, int numberOfTickets) {
        this.customerName = customerName;
        this.email = email;
        this.eventId = eventId;
        this.numberOfTickets = numberOfTickets;
    }

    /**
     * Gets the unique identifier of the booking.
     *
     * @return The booking ID.
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the booking.
     *
     * @param id The booking ID to set.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Gets the name of the customer making the booking.
     *
     * @return The customer name.
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the name of the customer making the booking.
     *
     * @param customerName The customer name to set.
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    
    /**
     * Gets the email of the customer making the booking.
     *
     * @return The customer email.
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email of the customer making the booking.
     *
     * @param email The customer email to set.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Gets the unique identifier of the event being booked.
     *
     * @return The event ID.
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * Sets the unique identifier of the event being booked.
     *
     * @param eventId The event ID to set.
     */
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    /**
     * Gets the number of tickets booked.
     *
     * @return The number of tickets.
     */
    public int getNumberOfTickets() {
        return numberOfTickets;
    }

    /**
     * Sets the number of tickets booked.
     *
     * @param numberOfTickets The number of tickets to set.
     */
    public void setNumberOfTickets(int numberOfTickets) {
        this.numberOfTickets = numberOfTickets;
    }
}