spring.application.name=WednesdaysWickedAdventures

spring.data.mongodb.uri=mongodb+srv://dbUser:dbpass123@eventdb.fbeeq.mongodb.net/?retryWrites=true&w=majority&appName=eventdb
spring.data.mongodb.database=eventdb

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method



spingdoc.show-actuator=true
management.endpoints.web.exposure.include=health, sbom, metrics, beans, env, scheduledtasks, shutdown 

#Under Development
spring.thymeleaf.cache=false


#management.endpoints.web.base-path=/details
#management.endpoint.health.group.custom.show-components=always
#management.endpoint.health.group.custom.show-details=always

#spring.thymeleaf.check-template-location=false

#spring.data.mongodb.uri=mongodb+srv://dbUser:dbpass123@eventdb.fbeeq.mongodb.net/?retryWrites=true&w=majority&appName=eventdb
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration, org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
#spring.data.mongodb.host=eventdb-shard-00-02.fbeeq.mongodb.net
#spring.data.mongodb.host=108.128.94.182
#spring.data.mongodb.port=27017

##spring.data.mongodb.uri=mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_CLUSTER}.mongodb.net/?retryWrites=true&w=majority
##spring.data.mongodb.database=${MONGODB_DATABASE}
#spring.data.mongodb.uri=mongodb+srv://dbUser:dbpass123@eventdb.fbeeq.mongodb.net/?sretryWrites=true&w=majority&appName=eventdb

###spring.data.mongodb.uri=mongodb+srv://dbUser:dbpass123@eventdb.fbeeq.mongodb.net?ssl=true&authSource=admin&retryWrites=true&w=majority&appName=eventdb
###spring.data.mongodb.database=eventdb

#spring.data.mongodb.uri=mongodb+srv://dbUser:dbpass123@eventdb.fbeeq.mongodb.net/?retryWrites=true&w=majority

#spring.data.mongodb.uri=mongodb://localhost:27017

#springdoc.swagger-ui.tagsSorter=alpha

#management.server.port=9090
#springdoc.use-management-port=true