package com.atu.WednesdaysWickedAdventures.model;

import java.time.LocalDateTime;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.Null;
import jakarta.validation.constraints.Size;

/**
 * Represents an EVENT entity in the Wednesdays Wicked Adventures system.
 * This class is mapped to the "events" collection in MongoDB.
 * 
 * @author	Mathieu Bizumuremyi 
 * @version	1.0 
 * @since	07-03-2025
 * 
 */
@Document(collection = "events")
public class Event {
    
    /**
     * The unique identifier of the event.
     * It must be null when creating a new event, as it is generated by the database.
     */
    @Id
    @Null(message = "Id must be null for events.")
    private String id;
    
    /**
     * The name of the event.
     * It must be between 5 and 250 characters long.
     */
    @Size(min = 5, max = 250, message = "Event name must be between 5 and 250 characters")
    private String name;
    
    /**
     * The venue of the event.
     */
    private String venue;
    /**
     * The date and time of the event.
     */
    private LocalDateTime dateTime;
    
    /**
     * The number of available tickets for the event.
     * It must be between 0 and 250.
     */
    @Min(value = 0, message = "availableTickets should not be less than 0")
    @Max(value = 250, message = "availableTickets should not be greater than 250")
    private int availableTickets;
    
    /**
     * Default constructor for the Event class.
     */
    public Event() {}
    
    /**
     * Constructs a new Event with the specified name, venue, date/time, and available tickets.
     *
     * @param name             The name of the event.
     * @param dateTime         The venue of the event.
     * @param dateTime         The date and time of the event.
     * @param availableTickets The number of available tickets.
     */
    public Event(String name, String venue, LocalDateTime dateTime, int availableTickets) {
        this.name = name;
        this.venue = venue;
        this.dateTime = dateTime;
        this.availableTickets = availableTickets;
    }

    /**
     * Gets the unique identifier of the event.
     *
     * @return The event ID.
     */
    public String getId() {
        return id;
    }
    
    /**
     * Sets the unique identifier of the event.
     *
     * @param id The event ID to set.
     */
    public void setId(String id) {
        this.id = id;
    }
    
    /**
     * Gets the name of the event.
     *
     * @return The event name.
     */
    public String getName() {
        return name;
    }
    
    /**
     * Sets the name of the event.
     *
     * @param name The event name to set.
     */
    public void setName(String name) {
        this.name = name;
    }
    
    /**
    * Gets the venue of the event.
    *
    * @return The event venue.
    */
   public String getVenue() {
       return venue;
   }
   
   /**
    * Sets the venue of the event.
    *
    * @param venue The event venue to set.
    */
   public void setVenue(String venue) {
       this.venue = venue;
   }
   
    /**
     * Gets the date and time of the event.
     *
     * @return The event date and time.
     */
    public LocalDateTime getDateTime() {
        return dateTime;
    }
    
    /**
     * Sets the date and time of the event.
     *
     * @param dateTime The event date and time to set.
     */
    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }
    
    /**
     * Gets the number of available tickets for the event.
     *
     * @return The number of available tickets.
     */
    public int getAvailableTickets() {
        return availableTickets;
    }
    
    /**
     * Sets the number of available tickets for the event.
     *
     * @param availableTickets The number of available tickets to set.
     */
    public void setAvailableTickets(int availableTickets) {
        this.availableTickets = availableTickets;
    }
}
